// cdefs.v — raw mlx-c bindings.
// Auto-generated by gen/gen_cdefs.py. Do not edit manually.

module mlx

// C struct typedefs (all opaque handles share a single `void* ctx`).

@[typedef]
struct C.mlx_array {
	ctx voidptr
}

@[typedef]
struct C.mlx_closure {
	ctx voidptr
}

@[typedef]
struct C.mlx_closure_custom {
	ctx voidptr
}

@[typedef]
struct C.mlx_closure_custom_jvp {
	ctx voidptr
}

@[typedef]
struct C.mlx_closure_custom_vmap {
	ctx voidptr
}

@[typedef]
struct C.mlx_closure_kwargs {
	ctx voidptr
}

@[typedef]
struct C.mlx_closure_value_and_grad {
	ctx voidptr
}

@[typedef]
struct C.mlx_device {
	ctx voidptr
}

@[typedef]
struct C.mlx_device_info {
	ctx voidptr
}

@[typedef]
struct C.mlx_distributed_group {
	ctx voidptr
}

@[typedef]
struct C.mlx_fast_cuda_kernel {
	ctx voidptr
}

@[typedef]
struct C.mlx_fast_cuda_kernel_config {
	ctx voidptr
}

@[typedef]
struct C.mlx_fast_metal_kernel {
	ctx voidptr
}

@[typedef]
struct C.mlx_fast_metal_kernel_config {
	ctx voidptr
}

@[typedef]
struct C.mlx_function_exporter {
	ctx voidptr
}

@[typedef]
struct C.mlx_imported_function {
	ctx voidptr
}

@[typedef]
struct C.mlx_io_gguf {
	ctx voidptr
}

@[typedef]
struct C.mlx_io_reader {
	ctx voidptr
}

@[typedef]
struct C.mlx_io_writer {
	ctx voidptr
}

@[typedef]
struct C.mlx_map_string_to_array {
	ctx voidptr
}

@[typedef]
struct C.mlx_map_string_to_array_iterator {
	ctx     voidptr
	map_ctx voidptr
}

@[typedef]
struct C.mlx_map_string_to_string {
	ctx voidptr
}

@[typedef]
struct C.mlx_map_string_to_string_iterator {
	ctx     voidptr
	map_ctx voidptr
}

@[typedef]
struct C.mlx_node_namer {
	ctx voidptr
}

@[typedef]
struct C.mlx_optional_dtype {
	value     int
	has_value bool
}

@[typedef]
struct C.mlx_optional_float {
	value     f32
	has_value bool
}

@[typedef]
struct C.mlx_optional_int {
	value     int
	has_value bool
}

@[typedef]
struct C.mlx_stream {
	ctx voidptr
}

@[typedef]
struct C.mlx_string {
	ctx voidptr
}

@[typedef]
struct C.mlx_vector_array {
	ctx voidptr
}

@[typedef]
struct C.mlx_vector_int {
	ctx voidptr
}

@[typedef]
struct C.mlx_vector_string {
	ctx voidptr
}

@[typedef]
struct C.mlx_vector_vector_array {
	ctx voidptr
}

// C function declarations.

fn C.mlx_string_new() C.mlx_string
fn C.mlx_string_new_data(str_ &char) C.mlx_string
fn C.mlx_string_set(str_ &C.mlx_string, src C.mlx_string) int
fn C.mlx_string_data(str_ C.mlx_string) &char
fn C.mlx_string_free(str_ C.mlx_string) int
fn C.mlx_dtype_size(dtype int) usize
fn C.mlx_array_tostring(str_ &C.mlx_string, arr C.mlx_array) int
fn C.mlx_array_new() C.mlx_array
fn C.mlx_array_free(arr C.mlx_array) int
fn C.mlx_array_new_bool(val bool) C.mlx_array
fn C.mlx_array_new_int(val int) C.mlx_array
fn C.mlx_array_new_float32(val f32) C.mlx_array
fn C.mlx_array_new_float(val f32) C.mlx_array
fn C.mlx_array_new_float64(val f64) C.mlx_array
fn C.mlx_array_new_double(val f64) C.mlx_array
fn C.mlx_array_new_complex(real_val f32, imag_val f32) C.mlx_array
fn C.mlx_array_new_data(data voidptr, shape &int, dim int, dtype int) C.mlx_array
fn C.mlx_array_set(arr &C.mlx_array, src C.mlx_array) int
fn C.mlx_array_set_bool(arr &C.mlx_array, val bool) int
fn C.mlx_array_set_int(arr &C.mlx_array, val int) int
fn C.mlx_array_set_float32(arr &C.mlx_array, val f32) int
fn C.mlx_array_set_float(arr &C.mlx_array, val f32) int
fn C.mlx_array_set_float64(arr &C.mlx_array, val f64) int
fn C.mlx_array_set_double(arr &C.mlx_array, val f64) int
fn C.mlx_array_set_complex(arr &C.mlx_array, real_val f32, imag_val f32) int
fn C.mlx_array_set_data(arr &C.mlx_array, data voidptr, shape &int, dim int, dtype int) int
fn C.mlx_array_itemsize(arr C.mlx_array) usize
fn C.mlx_array_size(arr C.mlx_array) usize
fn C.mlx_array_nbytes(arr C.mlx_array) usize
fn C.mlx_array_ndim(arr C.mlx_array) usize
fn C.mlx_array_shape(arr C.mlx_array) &int
fn C.mlx_array_strides(arr C.mlx_array) &usize
fn C.mlx_array_dim(arr C.mlx_array, dim int) int
fn C.mlx_array_dtype(arr C.mlx_array) int
fn C.mlx_array_eval(arr C.mlx_array) int
fn C.mlx_array_item_bool(res &bool, arr C.mlx_array) int
fn C.mlx_array_item_uint8(res &u8, arr C.mlx_array) int
fn C.mlx_array_item_uint16(res &u16, arr C.mlx_array) int
fn C.mlx_array_item_uint32(res &u32, arr C.mlx_array) int
fn C.mlx_array_item_uint64(res &u64, arr C.mlx_array) int
fn C.mlx_array_item_int8(res &i8, arr C.mlx_array) int
fn C.mlx_array_item_int16(res &i16, arr C.mlx_array) int
fn C.mlx_array_item_int32(res &int, arr C.mlx_array) int
fn C.mlx_array_item_int64(res &i64, arr C.mlx_array) int
fn C.mlx_array_item_float32(res &f32, arr C.mlx_array) int
fn C.mlx_array_item_float64(res &f64, arr C.mlx_array) int
fn C.mlx_array_data_bool(arr C.mlx_array) &bool
fn C.mlx_array_data_uint8(arr C.mlx_array) &u8
fn C.mlx_array_data_uint16(arr C.mlx_array) &u16
fn C.mlx_array_data_uint32(arr C.mlx_array) &u32
fn C.mlx_array_data_uint64(arr C.mlx_array) &u64
fn C.mlx_array_data_int8(arr C.mlx_array) &i8
fn C.mlx_array_data_int16(arr C.mlx_array) &i16
fn C.mlx_array_data_int32(arr C.mlx_array) &int
fn C.mlx_array_data_int64(arr C.mlx_array) &i64
fn C.mlx_array_data_float32(arr C.mlx_array) &f32
fn C.mlx_array_data_float64(arr C.mlx_array) &f64
fn C._mlx_array_is_available(res &bool, arr C.mlx_array) int
fn C._mlx_array_wait(arr C.mlx_array) int
fn C._mlx_array_is_contiguous(res &bool, arr C.mlx_array) int
fn C._mlx_array_is_row_contiguous(res &bool, arr C.mlx_array) int
fn C._mlx_array_is_col_contiguous(res &bool, arr C.mlx_array) int
fn C.mlx_vector_array_new() C.mlx_vector_array
fn C.mlx_vector_array_set(vec &C.mlx_vector_array, src C.mlx_vector_array) int
fn C.mlx_vector_array_free(vec C.mlx_vector_array) int
fn C.mlx_vector_array_new_data(data &C.mlx_array, size usize) C.mlx_vector_array
fn C.mlx_vector_array_new_value(val C.mlx_array) C.mlx_vector_array
fn C.mlx_vector_array_set_data(vec &C.mlx_vector_array, data &C.mlx_array, size usize) int
fn C.mlx_vector_array_set_value(vec &C.mlx_vector_array, val C.mlx_array) int
fn C.mlx_vector_array_append_data(vec C.mlx_vector_array, data &C.mlx_array, size usize) int
fn C.mlx_vector_array_append_value(vec C.mlx_vector_array, val C.mlx_array) int
fn C.mlx_vector_array_size(vec C.mlx_vector_array) usize
fn C.mlx_vector_array_get(res &C.mlx_array, vec C.mlx_vector_array, idx usize) int
fn C.mlx_vector_vector_array_new() C.mlx_vector_vector_array
fn C.mlx_vector_vector_array_set(vec &C.mlx_vector_vector_array, src C.mlx_vector_vector_array) int
fn C.mlx_vector_vector_array_free(vec C.mlx_vector_vector_array) int
fn C.mlx_vector_vector_array_new_data(data &C.mlx_vector_array, size usize) C.mlx_vector_vector_array
fn C.mlx_vector_vector_array_new_value(val C.mlx_vector_array) C.mlx_vector_vector_array
fn C.mlx_vector_vector_array_set_data(vec &C.mlx_vector_vector_array, data &C.mlx_vector_array, size usize) int
fn C.mlx_vector_vector_array_set_value(vec &C.mlx_vector_vector_array, val C.mlx_vector_array) int
fn C.mlx_vector_vector_array_append_data(vec C.mlx_vector_vector_array, data &C.mlx_vector_array, size usize) int
fn C.mlx_vector_vector_array_append_value(vec C.mlx_vector_vector_array, val C.mlx_vector_array) int
fn C.mlx_vector_vector_array_size(vec C.mlx_vector_vector_array) usize
fn C.mlx_vector_vector_array_get(res &C.mlx_vector_array, vec C.mlx_vector_vector_array, idx usize) int
fn C.mlx_vector_int_new() C.mlx_vector_int
fn C.mlx_vector_int_set(vec &C.mlx_vector_int, src C.mlx_vector_int) int
fn C.mlx_vector_int_free(vec C.mlx_vector_int) int
fn C.mlx_vector_int_new_data(data &int, size usize) C.mlx_vector_int
fn C.mlx_vector_int_new_value(val int) C.mlx_vector_int
fn C.mlx_vector_int_set_data(vec &C.mlx_vector_int, data &int, size usize) int
fn C.mlx_vector_int_set_value(vec &C.mlx_vector_int, val int) int
fn C.mlx_vector_int_append_data(vec C.mlx_vector_int, data &int, size usize) int
fn C.mlx_vector_int_append_value(vec C.mlx_vector_int, val int) int
fn C.mlx_vector_int_size(vec C.mlx_vector_int) usize
fn C.mlx_vector_int_get(res &int, vec C.mlx_vector_int, idx usize) int
fn C.mlx_vector_string_new() C.mlx_vector_string
fn C.mlx_vector_string_set(vec &C.mlx_vector_string, src C.mlx_vector_string) int
fn C.mlx_vector_string_free(vec C.mlx_vector_string) int
fn C.mlx_vector_string_new_data(data &&char, size usize) C.mlx_vector_string
fn C.mlx_vector_string_new_value(val &char) C.mlx_vector_string
fn C.mlx_vector_string_set_data(vec &C.mlx_vector_string, data &&char, size usize) int
fn C.mlx_vector_string_set_value(vec &C.mlx_vector_string, val &char) int
fn C.mlx_vector_string_append_data(vec C.mlx_vector_string, data &&char, size usize) int
fn C.mlx_vector_string_append_value(vec C.mlx_vector_string, val &char) int
fn C.mlx_vector_string_size(vec C.mlx_vector_string) usize
fn C.mlx_vector_string_get(res &&char, vec C.mlx_vector_string, idx usize) int
fn C.mlx_map_string_to_array_new() C.mlx_map_string_to_array
fn C.mlx_map_string_to_array_set(map_ &C.mlx_map_string_to_array, src C.mlx_map_string_to_array) int
fn C.mlx_map_string_to_array_free(map_ C.mlx_map_string_to_array) int
fn C.mlx_map_string_to_array_insert(map_ C.mlx_map_string_to_array, key &char, value C.mlx_array) int
fn C.mlx_map_string_to_array_get(value &C.mlx_array, map_ C.mlx_map_string_to_array, key &char) int
fn C.mlx_map_string_to_array_iterator_new(map_ C.mlx_map_string_to_array) C.mlx_map_string_to_array_iterator
fn C.mlx_map_string_to_array_iterator_free(it C.mlx_map_string_to_array_iterator) int
fn C.mlx_map_string_to_array_iterator_next(key &&char, value &C.mlx_array, it C.mlx_map_string_to_array_iterator) int
fn C.mlx_map_string_to_string_new() C.mlx_map_string_to_string
fn C.mlx_map_string_to_string_set(map_ &C.mlx_map_string_to_string, src C.mlx_map_string_to_string) int
fn C.mlx_map_string_to_string_free(map_ C.mlx_map_string_to_string) int
fn C.mlx_map_string_to_string_insert(map_ C.mlx_map_string_to_string, key &char, value &char) int
fn C.mlx_map_string_to_string_get(value &&char, map_ C.mlx_map_string_to_string, key &char) int
fn C.mlx_map_string_to_string_iterator_new(map_ C.mlx_map_string_to_string) C.mlx_map_string_to_string_iterator
fn C.mlx_map_string_to_string_iterator_free(it C.mlx_map_string_to_string_iterator) int
fn C.mlx_map_string_to_string_iterator_next(key &&char, value &&char, it C.mlx_map_string_to_string_iterator) int
fn C.mlx_device_new() C.mlx_device
fn C.mlx_device_new_type(type_ int, index int) C.mlx_device
fn C.mlx_device_free(dev C.mlx_device) int
fn C.mlx_device_set(dev &C.mlx_device, src C.mlx_device) int
fn C.mlx_device_tostring(str_ &C.mlx_string, dev C.mlx_device) int
fn C.mlx_device_equal(lhs C.mlx_device, rhs C.mlx_device) bool
fn C.mlx_device_get_index(index &int, dev C.mlx_device) int
fn C.mlx_device_get_type(type_ &int, dev C.mlx_device) int
fn C.mlx_get_default_device(dev &C.mlx_device) int
fn C.mlx_set_default_device(dev C.mlx_device) int
fn C.mlx_device_is_available(avail &bool, dev C.mlx_device) int
fn C.mlx_device_count(count &int, type_ int) int
fn C.mlx_device_info_new() C.mlx_device_info
fn C.mlx_device_info_get(info &C.mlx_device_info, dev C.mlx_device) int
fn C.mlx_device_info_free(info C.mlx_device_info) int
fn C.mlx_device_info_has_key(exists &bool, info C.mlx_device_info, key &char) int
fn C.mlx_device_info_is_string(is_string &bool, info C.mlx_device_info, key &char) int
fn C.mlx_device_info_get_string(value &&char, info C.mlx_device_info, key &char) int
fn C.mlx_device_info_get_size(value &usize, info C.mlx_device_info, key &char) int
fn C.mlx_device_info_get_keys(keys &C.mlx_vector_string, info C.mlx_device_info) int
fn C.mlx_stream_new() C.mlx_stream
fn C.mlx_stream_new_device(dev C.mlx_device) C.mlx_stream
fn C.mlx_stream_set(stream &C.mlx_stream, src C.mlx_stream) int
fn C.mlx_stream_free(stream C.mlx_stream) int
fn C.mlx_stream_tostring(str_ &C.mlx_string, stream C.mlx_stream) int
fn C.mlx_stream_equal(lhs C.mlx_stream, rhs C.mlx_stream) bool
fn C.mlx_stream_get_device(dev &C.mlx_device, stream C.mlx_stream) int
fn C.mlx_stream_get_index(index &int, stream C.mlx_stream) int
fn C.mlx_synchronize(stream C.mlx_stream) int
fn C.mlx_get_default_stream(stream &C.mlx_stream, dev C.mlx_device) int
fn C.mlx_set_default_stream(stream C.mlx_stream) int
fn C.mlx_default_cpu_stream_new() C.mlx_stream
fn C.mlx_default_gpu_stream_new() C.mlx_stream
fn C.mlx_io_reader_descriptor(desc_ &voidptr, io C.mlx_io_reader) int
fn C.mlx_io_reader_tostring(str_ &C.mlx_string, io C.mlx_io_reader) int
fn C.mlx_io_reader_free(io C.mlx_io_reader) int
fn C.mlx_io_writer_descriptor(desc_ &voidptr, io C.mlx_io_writer) int
fn C.mlx_io_writer_tostring(str_ &C.mlx_string, io C.mlx_io_writer) int
fn C.mlx_io_writer_free(io C.mlx_io_writer) int
fn C.mlx_io_gguf_new() C.mlx_io_gguf
fn C.mlx_io_gguf_free(io C.mlx_io_gguf) int
fn C.mlx_io_gguf_get_keys(keys &C.mlx_vector_string, io C.mlx_io_gguf) int
fn C.mlx_io_gguf_get_array(arr &C.mlx_array, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_get_metadata_array(arr &C.mlx_array, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_get_metadata_string(str_ &C.mlx_string, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_get_metadata_vector_string(vstr &C.mlx_vector_string, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_has_metadata_array(flag &bool, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_has_metadata_string(flag &bool, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_has_metadata_vector_string(flag &bool, io C.mlx_io_gguf, key &char) int
fn C.mlx_io_gguf_set_array(io C.mlx_io_gguf, key &char, arr C.mlx_array) int
fn C.mlx_io_gguf_set_metadata_array(io C.mlx_io_gguf, key &char, marr C.mlx_array) int
fn C.mlx_io_gguf_set_metadata_string(io C.mlx_io_gguf, key &char, mstr &char) int
fn C.mlx_io_gguf_set_metadata_vector_string(io C.mlx_io_gguf, key &char, mvstr C.mlx_vector_string) int
fn C.mlx_distributed_group_new() C.mlx_distributed_group
fn C.mlx_distributed_group_free(group C.mlx_distributed_group) int
fn C.mlx_distributed_init(res &C.mlx_distributed_group, strict bool, bk &char) int
fn C.mlx_distributed_group_rank(group C.mlx_distributed_group) int
fn C.mlx_distributed_group_size(group C.mlx_distributed_group) int
fn C.mlx_distributed_group_split(res &C.mlx_distributed_group, group C.mlx_distributed_group, color int, key int) int
fn C.mlx_distributed_is_available(bk &char) bool
fn C.mlx_closure_new() C.mlx_closure
fn C.mlx_closure_free(cls C.mlx_closure) int
fn C.mlx_closure_set(cls &C.mlx_closure, src C.mlx_closure) int
fn C.mlx_closure_apply(res &C.mlx_vector_array, cls C.mlx_closure, input C.mlx_vector_array) int
fn C.mlx_closure_kwargs_new() C.mlx_closure_kwargs
fn C.mlx_closure_kwargs_free(cls C.mlx_closure_kwargs) int
fn C.mlx_closure_kwargs_set(cls &C.mlx_closure_kwargs, src C.mlx_closure_kwargs) int
fn C.mlx_closure_kwargs_apply(res &C.mlx_vector_array, cls C.mlx_closure_kwargs, input_0 C.mlx_vector_array, input_1 C.mlx_map_string_to_array) int
fn C.mlx_closure_value_and_grad_new() C.mlx_closure_value_and_grad
fn C.mlx_closure_value_and_grad_free(cls C.mlx_closure_value_and_grad) int
fn C.mlx_closure_value_and_grad_set(cls &C.mlx_closure_value_and_grad, src C.mlx_closure_value_and_grad) int
fn C.mlx_closure_value_and_grad_apply(res_0 &C.mlx_vector_array, res_1 &C.mlx_vector_array, cls C.mlx_closure_value_and_grad, input C.mlx_vector_array) int
fn C.mlx_closure_custom_new() C.mlx_closure_custom
fn C.mlx_closure_custom_free(cls C.mlx_closure_custom) int
fn C.mlx_closure_custom_set(cls &C.mlx_closure_custom, src C.mlx_closure_custom) int
fn C.mlx_closure_custom_apply(res &C.mlx_vector_array, cls C.mlx_closure_custom, input_0 C.mlx_vector_array, input_1 C.mlx_vector_array, input_2 C.mlx_vector_array) int
fn C.mlx_closure_custom_jvp_new() C.mlx_closure_custom_jvp
fn C.mlx_closure_custom_jvp_free(cls C.mlx_closure_custom_jvp) int
fn C.mlx_closure_custom_jvp_set(cls &C.mlx_closure_custom_jvp, src C.mlx_closure_custom_jvp) int
fn C.mlx_closure_custom_jvp_apply(res &C.mlx_vector_array, cls C.mlx_closure_custom_jvp, input_0 C.mlx_vector_array, input_1 C.mlx_vector_array, input_2 &int, input_2_num usize) int
fn C.mlx_closure_custom_vmap_new() C.mlx_closure_custom_vmap
fn C.mlx_closure_custom_vmap_free(cls C.mlx_closure_custom_vmap) int
fn C.mlx_closure_custom_vmap_set(cls &C.mlx_closure_custom_vmap, src C.mlx_closure_custom_vmap) int
fn C.mlx_closure_custom_vmap_apply(res_0 &C.mlx_vector_array, res_1 &C.mlx_vector_int, cls C.mlx_closure_custom_vmap, input_0 C.mlx_vector_array, input_1 &int, input_1_num usize) int
fn C.mlx_abs(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_add(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_addmm(res &C.mlx_array, c C.mlx_array, a C.mlx_array, b C.mlx_array, alpha f32, beta f32, s C.mlx_stream) int
fn C.mlx_all_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_all_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_all(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_allclose(res &C.mlx_array, a C.mlx_array, b C.mlx_array, rtol f64, atol f64, equal_nan bool, s C.mlx_stream) int
fn C.mlx_any_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_any_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_any(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_arange(res &C.mlx_array, start f64, stop f64, step f64, dtype int, s C.mlx_stream) int
fn C.mlx_arccos(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_arccosh(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_arcsin(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_arcsinh(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_arctan(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_arctan2(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_arctanh(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_argmax_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_argmax(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_argmin_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_argmin(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_argpartition_axis(res &C.mlx_array, a C.mlx_array, kth int, axis int, s C.mlx_stream) int
fn C.mlx_argpartition(res &C.mlx_array, a C.mlx_array, kth int, s C.mlx_stream) int
fn C.mlx_argsort_axis(res &C.mlx_array, a C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_argsort(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_array_equal(res &C.mlx_array, a C.mlx_array, b C.mlx_array, equal_nan bool, s C.mlx_stream) int
fn C.mlx_as_strided(res &C.mlx_array, a C.mlx_array, shape &int, shape_num usize, strides &i64, strides_num usize, offset usize, s C.mlx_stream) int
fn C.mlx_astype(res &C.mlx_array, a C.mlx_array, dtype int, s C.mlx_stream) int
fn C.mlx_atleast_1d(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_atleast_2d(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_atleast_3d(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_bartlett(res &C.mlx_array, M int, s C.mlx_stream) int
fn C.mlx_bitwise_and(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_bitwise_invert(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_bitwise_or(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_bitwise_xor(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_blackman(res &C.mlx_array, M int, s C.mlx_stream) int
fn C.mlx_block_masked_mm(res &C.mlx_array, a C.mlx_array, b C.mlx_array, block_size int, mask_out C.mlx_array, mask_lhs C.mlx_array, mask_rhs C.mlx_array, s C.mlx_stream) int
fn C.mlx_broadcast_arrays(res &C.mlx_vector_array, inputs C.mlx_vector_array, s C.mlx_stream) int
fn C.mlx_broadcast_to(res &C.mlx_array, a C.mlx_array, shape &int, shape_num usize, s C.mlx_stream) int
fn C.mlx_ceil(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_clip(res &C.mlx_array, a C.mlx_array, a_min C.mlx_array, a_max C.mlx_array, s C.mlx_stream) int
fn C.mlx_concatenate_axis(res &C.mlx_array, arrays C.mlx_vector_array, axis int, s C.mlx_stream) int
fn C.mlx_concatenate(res &C.mlx_array, arrays C.mlx_vector_array, s C.mlx_stream) int
fn C.mlx_conjugate(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_contiguous(res &C.mlx_array, a C.mlx_array, allow_col_major bool, s C.mlx_stream) int
fn C.mlx_conv1d(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride int, padding int, dilation int, groups int, s C.mlx_stream) int
fn C.mlx_conv2d(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride_0 int, stride_1 int, padding_0 int, padding_1 int, dilation_0 int, dilation_1 int, groups int, s C.mlx_stream) int
fn C.mlx_conv3d(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride_0 int, stride_1 int, stride_2 int, padding_0 int, padding_1 int, padding_2 int, dilation_0 int, dilation_1 int, dilation_2 int, groups int, s C.mlx_stream) int
fn C.mlx_conv_general(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride &int, stride_num usize, padding_lo &int, padding_lo_num usize, padding_hi &int, padding_hi_num usize, kernel_dilation &int, kernel_dilation_num usize, input_dilation &int, input_dilation_num usize, groups int, flip bool, s C.mlx_stream) int
fn C.mlx_conv_transpose1d(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride int, padding int, dilation int, output_padding int, groups int, s C.mlx_stream) int
fn C.mlx_conv_transpose2d(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride_0 int, stride_1 int, padding_0 int, padding_1 int, dilation_0 int, dilation_1 int, output_padding_0 int, output_padding_1 int, groups int, s C.mlx_stream) int
fn C.mlx_conv_transpose3d(res &C.mlx_array, input C.mlx_array, weight C.mlx_array, stride_0 int, stride_1 int, stride_2 int, padding_0 int, padding_1 int, padding_2 int, dilation_0 int, dilation_1 int, dilation_2 int, output_padding_0 int, output_padding_1 int, output_padding_2 int, groups int, s C.mlx_stream) int
fn C.mlx_copy(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_cos(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_cosh(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_cummax(res &C.mlx_array, a C.mlx_array, axis int, reverse bool, inclusive bool, s C.mlx_stream) int
fn C.mlx_cummin(res &C.mlx_array, a C.mlx_array, axis int, reverse bool, inclusive bool, s C.mlx_stream) int
fn C.mlx_cumprod(res &C.mlx_array, a C.mlx_array, axis int, reverse bool, inclusive bool, s C.mlx_stream) int
fn C.mlx_cumsum(res &C.mlx_array, a C.mlx_array, axis int, reverse bool, inclusive bool, s C.mlx_stream) int
fn C.mlx_degrees(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_depends(res &C.mlx_vector_array, inputs C.mlx_vector_array, dependencies C.mlx_vector_array) int
fn C.mlx_dequantize(res &C.mlx_array, w C.mlx_array, scales C.mlx_array, biases C.mlx_array, group_size C.mlx_optional_int, bits C.mlx_optional_int, mode &char, global_scale C.mlx_array, dtype C.mlx_optional_dtype, s C.mlx_stream) int
fn C.mlx_diag(res &C.mlx_array, a C.mlx_array, k int, s C.mlx_stream) int
fn C.mlx_diagonal(res &C.mlx_array, a C.mlx_array, offset int, axis1 int, axis2 int, s C.mlx_stream) int
fn C.mlx_divide(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_divmod(res &C.mlx_vector_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_einsum(res &C.mlx_array, subscripts &char, operands C.mlx_vector_array, s C.mlx_stream) int
fn C.mlx_equal(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_erf(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_erfinv(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_exp(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_expand_dims_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_expand_dims(res &C.mlx_array, a C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_expm1(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_eye(res &C.mlx_array, n int, m int, k int, dtype int, s C.mlx_stream) int
fn C.mlx_flatten(res &C.mlx_array, a C.mlx_array, start_axis int, end_axis int, s C.mlx_stream) int
fn C.mlx_floor(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_floor_divide(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_from_fp8(res &C.mlx_array, x C.mlx_array, dtype int, s C.mlx_stream) int
fn C.mlx_full(res &C.mlx_array, shape &int, shape_num usize, vals C.mlx_array, dtype int, s C.mlx_stream) int
fn C.mlx_full_like(res &C.mlx_array, a C.mlx_array, vals C.mlx_array, dtype int, s C.mlx_stream) int
fn C.mlx_gather(res &C.mlx_array, a C.mlx_array, indices C.mlx_vector_array, axes &int, axes_num usize, slice_sizes &int, slice_sizes_num usize, s C.mlx_stream) int
fn C.mlx_gather_single(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, axis int, slice_sizes &int, slice_sizes_num usize, s C.mlx_stream) int
fn C.mlx_gather_mm(res &C.mlx_array, a C.mlx_array, b C.mlx_array, lhs_indices C.mlx_array, rhs_indices C.mlx_array, sorted_indices bool, s C.mlx_stream) int
fn C.mlx_gather_qmm(res &C.mlx_array, x C.mlx_array, w C.mlx_array, scales C.mlx_array, biases C.mlx_array, lhs_indices C.mlx_array, rhs_indices C.mlx_array, transpose bool, group_size C.mlx_optional_int, bits C.mlx_optional_int, mode &char, sorted_indices bool, s C.mlx_stream) int
fn C.mlx_greater(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_greater_equal(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_hadamard_transform(res &C.mlx_array, a C.mlx_array, scale C.mlx_optional_float, s C.mlx_stream) int
fn C.mlx_hamming(res &C.mlx_array, M int, s C.mlx_stream) int
fn C.mlx_hanning(res &C.mlx_array, M int, s C.mlx_stream) int
fn C.mlx_identity(res &C.mlx_array, n int, dtype int, s C.mlx_stream) int
fn C.mlx_imag(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_inner(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_isclose(res &C.mlx_array, a C.mlx_array, b C.mlx_array, rtol f64, atol f64, equal_nan bool, s C.mlx_stream) int
fn C.mlx_isfinite(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_isinf(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_isnan(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_isneginf(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_isposinf(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_kron(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_left_shift(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_less(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_less_equal(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_linspace(res &C.mlx_array, start f64, stop f64, num int, dtype int, s C.mlx_stream) int
fn C.mlx_log(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_log10(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_log1p(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_log2(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_logaddexp(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_logcumsumexp(res &C.mlx_array, a C.mlx_array, axis int, reverse bool, inclusive bool, s C.mlx_stream) int
fn C.mlx_logical_and(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_logical_not(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_logical_or(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_logsumexp_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_logsumexp_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_logsumexp(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_masked_scatter(res &C.mlx_array, a C.mlx_array, mask C.mlx_array, src C.mlx_array, s C.mlx_stream) int
fn C.mlx_matmul(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_max_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_max_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_max(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_maximum(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_mean_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_mean_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_mean(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_median(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_meshgrid(res &C.mlx_vector_array, arrays C.mlx_vector_array, sparse bool, indexing &char, s C.mlx_stream) int
fn C.mlx_min_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_min_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_min(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_minimum(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_moveaxis(res &C.mlx_array, a C.mlx_array, source int, destination int, s C.mlx_stream) int
fn C.mlx_multiply(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_nan_to_num(res &C.mlx_array, a C.mlx_array, nan f32, posinf C.mlx_optional_float, neginf C.mlx_optional_float, s C.mlx_stream) int
fn C.mlx_negative(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_not_equal(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_number_of_elements(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, inverted bool, dtype int, s C.mlx_stream) int
fn C.mlx_ones(res &C.mlx_array, shape &int, shape_num usize, dtype int, s C.mlx_stream) int
fn C.mlx_ones_like(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_outer(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_pad(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, low_pad_size &int, low_pad_size_num usize, high_pad_size &int, high_pad_size_num usize, pad_value C.mlx_array, mode &char, s C.mlx_stream) int
fn C.mlx_pad_symmetric(res &C.mlx_array, a C.mlx_array, pad_width int, pad_value C.mlx_array, mode &char, s C.mlx_stream) int
fn C.mlx_partition_axis(res &C.mlx_array, a C.mlx_array, kth int, axis int, s C.mlx_stream) int
fn C.mlx_partition(res &C.mlx_array, a C.mlx_array, kth int, s C.mlx_stream) int
fn C.mlx_power(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_prod_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_prod_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_prod(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_put_along_axis(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, values C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_qqmm(res &C.mlx_array, x C.mlx_array, w C.mlx_array, w_scales C.mlx_array, group_size C.mlx_optional_int, bits C.mlx_optional_int, mode &char, global_scale_x C.mlx_array, global_scale_w C.mlx_array, s C.mlx_stream) int
fn C.mlx_quantize(res &C.mlx_vector_array, w C.mlx_array, group_size C.mlx_optional_int, bits C.mlx_optional_int, mode &char, global_scale C.mlx_array, s C.mlx_stream) int
fn C.mlx_quantized_matmul(res &C.mlx_array, x C.mlx_array, w C.mlx_array, scales C.mlx_array, biases C.mlx_array, transpose bool, group_size C.mlx_optional_int, bits C.mlx_optional_int, mode &char, s C.mlx_stream) int
fn C.mlx_radians(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_real(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_reciprocal(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_remainder(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_repeat_axis(res &C.mlx_array, arr C.mlx_array, repeats int, axis int, s C.mlx_stream) int
fn C.mlx_repeat(res &C.mlx_array, arr C.mlx_array, repeats int, s C.mlx_stream) int
fn C.mlx_reshape(res &C.mlx_array, a C.mlx_array, shape &int, shape_num usize, s C.mlx_stream) int
fn C.mlx_right_shift(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_roll_axis(res &C.mlx_array, a C.mlx_array, shift &int, shift_num usize, axis int, s C.mlx_stream) int
fn C.mlx_roll_axes(res &C.mlx_array, a C.mlx_array, shift &int, shift_num usize, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_roll(res &C.mlx_array, a C.mlx_array, shift &int, shift_num usize, s C.mlx_stream) int
fn C.mlx_round(res &C.mlx_array, a C.mlx_array, decimals int, s C.mlx_stream) int
fn C.mlx_rsqrt(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_scatter(res &C.mlx_array, a C.mlx_array, indices C.mlx_vector_array, updates C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_scatter_single(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, updates C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_scatter_add(res &C.mlx_array, a C.mlx_array, indices C.mlx_vector_array, updates C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_scatter_add_single(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, updates C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_scatter_add_axis(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, values C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_scatter_max(res &C.mlx_array, a C.mlx_array, indices C.mlx_vector_array, updates C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_scatter_max_single(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, updates C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_scatter_min(res &C.mlx_array, a C.mlx_array, indices C.mlx_vector_array, updates C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_scatter_min_single(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, updates C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_scatter_prod(res &C.mlx_array, a C.mlx_array, indices C.mlx_vector_array, updates C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_scatter_prod_single(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, updates C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_segmented_mm(res &C.mlx_array, a C.mlx_array, b C.mlx_array, segments C.mlx_array, s C.mlx_stream) int
fn C.mlx_sigmoid(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_sign(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_sin(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_sinh(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_slice(res &C.mlx_array, a C.mlx_array, start &int, start_num usize, stop &int, stop_num usize, strides &int, strides_num usize, s C.mlx_stream) int
fn C.mlx_slice_dynamic(res &C.mlx_array, a C.mlx_array, start C.mlx_array, axes &int, axes_num usize, slice_size &int, slice_size_num usize, s C.mlx_stream) int
fn C.mlx_slice_update(res &C.mlx_array, src C.mlx_array, update C.mlx_array, start &int, start_num usize, stop &int, stop_num usize, strides &int, strides_num usize, s C.mlx_stream) int
fn C.mlx_slice_update_dynamic(res &C.mlx_array, src C.mlx_array, update C.mlx_array, start C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_slice_update_add(res &C.mlx_array, src C.mlx_array, update C.mlx_array, start &int, start_num usize, stop &int, stop_num usize, strides &int, strides_num usize, s C.mlx_stream) int
fn C.mlx_slice_update_max(res &C.mlx_array, src C.mlx_array, update C.mlx_array, start &int, start_num usize, stop &int, stop_num usize, strides &int, strides_num usize, s C.mlx_stream) int
fn C.mlx_slice_update_min(res &C.mlx_array, src C.mlx_array, update C.mlx_array, start &int, start_num usize, stop &int, stop_num usize, strides &int, strides_num usize, s C.mlx_stream) int
fn C.mlx_slice_update_prod(res &C.mlx_array, src C.mlx_array, update C.mlx_array, start &int, start_num usize, stop &int, stop_num usize, strides &int, strides_num usize, s C.mlx_stream) int
fn C.mlx_softmax_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, precise bool, s C.mlx_stream) int
fn C.mlx_softmax_axis(res &C.mlx_array, a C.mlx_array, axis int, precise bool, s C.mlx_stream) int
fn C.mlx_softmax(res &C.mlx_array, a C.mlx_array, precise bool, s C.mlx_stream) int
fn C.mlx_sort_axis(res &C.mlx_array, a C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_sort(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_split(res &C.mlx_vector_array, a C.mlx_array, num_splits int, axis int, s C.mlx_stream) int
fn C.mlx_split_sections(res &C.mlx_vector_array, a C.mlx_array, indices &int, indices_num usize, axis int, s C.mlx_stream) int
fn C.mlx_sqrt(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_square(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_squeeze_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_squeeze_axis(res &C.mlx_array, a C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_squeeze(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_stack_axis(res &C.mlx_array, arrays C.mlx_vector_array, axis int, s C.mlx_stream) int
fn C.mlx_stack(res &C.mlx_array, arrays C.mlx_vector_array, s C.mlx_stream) int
fn C.mlx_std_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, ddof int, s C.mlx_stream) int
fn C.mlx_std_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, ddof int, s C.mlx_stream) int
fn C.mlx_std(res &C.mlx_array, a C.mlx_array, keepdims bool, ddof int, s C.mlx_stream) int
fn C.mlx_stop_gradient(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_subtract(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_sum_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_sum_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, s C.mlx_stream) int
fn C.mlx_sum(res &C.mlx_array, a C.mlx_array, keepdims bool, s C.mlx_stream) int
fn C.mlx_swapaxes(res &C.mlx_array, a C.mlx_array, axis1 int, axis2 int, s C.mlx_stream) int
fn C.mlx_take_axis(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_take(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, s C.mlx_stream) int
fn C.mlx_take_along_axis(res &C.mlx_array, a C.mlx_array, indices C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_tan(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_tanh(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_tensordot(res &C.mlx_array, a C.mlx_array, b C.mlx_array, axes_a &int, axes_a_num usize, axes_b &int, axes_b_num usize, s C.mlx_stream) int
fn C.mlx_tensordot_axis(res &C.mlx_array, a C.mlx_array, b C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_tile(res &C.mlx_array, arr C.mlx_array, reps &int, reps_num usize, s C.mlx_stream) int
fn C.mlx_to_fp8(res &C.mlx_array, x C.mlx_array, s C.mlx_stream) int
fn C.mlx_topk_axis(res &C.mlx_array, a C.mlx_array, k int, axis int, s C.mlx_stream) int
fn C.mlx_topk(res &C.mlx_array, a C.mlx_array, k int, s C.mlx_stream) int
fn C.mlx_trace(res &C.mlx_array, a C.mlx_array, offset int, axis1 int, axis2 int, dtype int, s C.mlx_stream) int
fn C.mlx_transpose_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_transpose(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_tri(res &C.mlx_array, n int, m int, k int, type_ int, s C.mlx_stream) int
fn C.mlx_tril(res &C.mlx_array, x C.mlx_array, k int, s C.mlx_stream) int
fn C.mlx_triu(res &C.mlx_array, x C.mlx_array, k int, s C.mlx_stream) int
fn C.mlx_unflatten(res &C.mlx_array, a C.mlx_array, axis int, shape &int, shape_num usize, s C.mlx_stream) int
fn C.mlx_var_axes(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, keepdims bool, ddof int, s C.mlx_stream) int
fn C.mlx_var_axis(res &C.mlx_array, a C.mlx_array, axis int, keepdims bool, ddof int, s C.mlx_stream) int
fn C.mlx_var(res &C.mlx_array, a C.mlx_array, keepdims bool, ddof int, s C.mlx_stream) int
fn C.mlx_view(res &C.mlx_array, a C.mlx_array, dtype int, s C.mlx_stream) int
fn C.mlx_where(res &C.mlx_array, condition C.mlx_array, x C.mlx_array, y C.mlx_array, s C.mlx_stream) int
fn C.mlx_zeros(res &C.mlx_array, shape &int, shape_num usize, dtype int, s C.mlx_stream) int
fn C.mlx_zeros_like(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_bernoulli(res &C.mlx_array, p C.mlx_array, shape &int, shape_num usize, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_bits(res &C.mlx_array, shape &int, shape_num usize, width int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_categorical_shape(res &C.mlx_array, logits C.mlx_array, axis int, shape &int, shape_num usize, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_categorical_num_samples(res &C.mlx_array, logits_ C.mlx_array, axis int, num_samples int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_categorical(res &C.mlx_array, logits C.mlx_array, axis int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_gumbel(res &C.mlx_array, shape &int, shape_num usize, dtype int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_key(res &C.mlx_array, seed u64) int
fn C.mlx_random_laplace(res &C.mlx_array, shape &int, shape_num usize, dtype int, loc f32, scale f32, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_multivariate_normal(res &C.mlx_array, mean C.mlx_array, cov C.mlx_array, shape &int, shape_num usize, dtype int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_normal_broadcast(res &C.mlx_array, shape &int, shape_num usize, dtype int, loc C.mlx_array, scale C.mlx_array, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_normal(res &C.mlx_array, shape &int, shape_num usize, dtype int, loc f32, scale f32, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_permutation(res &C.mlx_array, x C.mlx_array, axis int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_permutation_arange(res &C.mlx_array, x int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_randint(res &C.mlx_array, low C.mlx_array, high C.mlx_array, shape &int, shape_num usize, dtype int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_seed(seed u64) int
fn C.mlx_random_split_num(res &C.mlx_array, key C.mlx_array, num int, s C.mlx_stream) int
fn C.mlx_random_split(res_0 &C.mlx_array, res_1 &C.mlx_array, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_truncated_normal(res &C.mlx_array, lower C.mlx_array, upper C.mlx_array, shape &int, shape_num usize, dtype int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_random_uniform(res &C.mlx_array, low C.mlx_array, high C.mlx_array, shape &int, shape_num usize, dtype int, key C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_cholesky(res &C.mlx_array, a C.mlx_array, upper bool, s C.mlx_stream) int
fn C.mlx_linalg_cholesky_inv(res &C.mlx_array, a C.mlx_array, upper bool, s C.mlx_stream) int
fn C.mlx_linalg_cross(res &C.mlx_array, a C.mlx_array, b C.mlx_array, axis int, s C.mlx_stream) int
fn C.mlx_linalg_eig(res_0 &C.mlx_array, res_1 &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_eigh(res_0 &C.mlx_array, res_1 &C.mlx_array, a C.mlx_array, UPLO &char, s C.mlx_stream) int
fn C.mlx_linalg_eigvals(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_eigvalsh(res &C.mlx_array, a C.mlx_array, UPLO &char, s C.mlx_stream) int
fn C.mlx_linalg_inv(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_lu(res &C.mlx_vector_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_lu_factor(res_0 &C.mlx_array, res_1 &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_norm(res &C.mlx_array, a C.mlx_array, ord f64, axis &int, axis_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_linalg_norm_matrix(res &C.mlx_array, a C.mlx_array, ord &char, axis &int, axis_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_linalg_norm_l2(res &C.mlx_array, a C.mlx_array, axis &int, axis_num usize, keepdims bool, s C.mlx_stream) int
fn C.mlx_linalg_pinv(res &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_qr(res_0 &C.mlx_array, res_1 &C.mlx_array, a C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_solve(res &C.mlx_array, a C.mlx_array, b C.mlx_array, s C.mlx_stream) int
fn C.mlx_linalg_solve_triangular(res &C.mlx_array, a C.mlx_array, b C.mlx_array, upper bool, s C.mlx_stream) int
fn C.mlx_linalg_svd(res &C.mlx_vector_array, a C.mlx_array, compute_uv bool, s C.mlx_stream) int
fn C.mlx_linalg_tri_inv(res &C.mlx_array, a C.mlx_array, upper bool, s C.mlx_stream) int
fn C.mlx_fft_fft(res &C.mlx_array, a C.mlx_array, n int, axis int, norm int, s C.mlx_stream) int
fn C.mlx_fft_fft2(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_fftfreq(res &C.mlx_array, n int, d f64, s C.mlx_stream) int
fn C.mlx_fft_fftn(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_fftshift(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_fft_ifft(res &C.mlx_array, a C.mlx_array, n int, axis int, norm int, s C.mlx_stream) int
fn C.mlx_fft_ifft2(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_ifftn(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_ifftshift(res &C.mlx_array, a C.mlx_array, axes &int, axes_num usize, s C.mlx_stream) int
fn C.mlx_fft_irfft(res &C.mlx_array, a C.mlx_array, n int, axis int, norm int, s C.mlx_stream) int
fn C.mlx_fft_irfft2(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_irfftn(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_rfft(res &C.mlx_array, a C.mlx_array, n int, axis int, norm int, s C.mlx_stream) int
fn C.mlx_fft_rfft2(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fft_rfftfreq(res &C.mlx_array, n int, d f64, s C.mlx_stream) int
fn C.mlx_fft_rfftn(res &C.mlx_array, a C.mlx_array, n &int, n_num usize, axes &int, axes_num usize, norm int, s C.mlx_stream) int
fn C.mlx_fast_cuda_kernel_config_new() C.mlx_fast_cuda_kernel_config
fn C.mlx_fast_cuda_kernel_config_free(cls C.mlx_fast_cuda_kernel_config)
fn C.mlx_fast_cuda_kernel_config_add_output_arg(cls C.mlx_fast_cuda_kernel_config, shape &int, size usize, dtype int) int
fn C.mlx_fast_cuda_kernel_config_set_grid(cls C.mlx_fast_cuda_kernel_config, grid1 int, grid2 int, grid3 int) int
fn C.mlx_fast_cuda_kernel_config_set_thread_group(cls C.mlx_fast_cuda_kernel_config, thread1 int, thread2 int, thread3 int) int
fn C.mlx_fast_cuda_kernel_config_set_init_value(cls C.mlx_fast_cuda_kernel_config, value f32) int
fn C.mlx_fast_cuda_kernel_config_set_verbose(cls C.mlx_fast_cuda_kernel_config, verbose bool) int
fn C.mlx_fast_cuda_kernel_config_add_template_arg_dtype(cls C.mlx_fast_cuda_kernel_config, name &char, dtype int) int
fn C.mlx_fast_cuda_kernel_config_add_template_arg_int(cls C.mlx_fast_cuda_kernel_config, name &char, value int) int
fn C.mlx_fast_cuda_kernel_config_add_template_arg_bool(cls C.mlx_fast_cuda_kernel_config, name &char, value bool) int
fn C.mlx_fast_cuda_kernel_new(name &char, input_names C.mlx_vector_string, output_names C.mlx_vector_string, source &char, header &char, ensure_row_contiguous bool, shared_memory int) C.mlx_fast_cuda_kernel
fn C.mlx_fast_cuda_kernel_free(cls C.mlx_fast_cuda_kernel)
fn C.mlx_fast_cuda_kernel_apply(outputs &C.mlx_vector_array, cls C.mlx_fast_cuda_kernel, inputs C.mlx_vector_array, config C.mlx_fast_cuda_kernel_config, stream C.mlx_stream) int
fn C.mlx_fast_layer_norm(res &C.mlx_array, x C.mlx_array, weight C.mlx_array, bias C.mlx_array, eps f32, s C.mlx_stream) int
fn C.mlx_fast_metal_kernel_config_new() C.mlx_fast_metal_kernel_config
fn C.mlx_fast_metal_kernel_config_free(cls C.mlx_fast_metal_kernel_config)
fn C.mlx_fast_metal_kernel_config_add_output_arg(cls C.mlx_fast_metal_kernel_config, shape &int, size usize, dtype int) int
fn C.mlx_fast_metal_kernel_config_set_grid(cls C.mlx_fast_metal_kernel_config, grid1 int, grid2 int, grid3 int) int
fn C.mlx_fast_metal_kernel_config_set_thread_group(cls C.mlx_fast_metal_kernel_config, thread1 int, thread2 int, thread3 int) int
fn C.mlx_fast_metal_kernel_config_set_init_value(cls C.mlx_fast_metal_kernel_config, value f32) int
fn C.mlx_fast_metal_kernel_config_set_verbose(cls C.mlx_fast_metal_kernel_config, verbose bool) int
fn C.mlx_fast_metal_kernel_config_add_template_arg_dtype(cls C.mlx_fast_metal_kernel_config, name &char, dtype int) int
fn C.mlx_fast_metal_kernel_config_add_template_arg_int(cls C.mlx_fast_metal_kernel_config, name &char, value int) int
fn C.mlx_fast_metal_kernel_config_add_template_arg_bool(cls C.mlx_fast_metal_kernel_config, name &char, value bool) int
fn C.mlx_fast_metal_kernel_new(name &char, input_names C.mlx_vector_string, output_names C.mlx_vector_string, source &char, header &char, ensure_row_contiguous bool, atomic_outputs bool) C.mlx_fast_metal_kernel
fn C.mlx_fast_metal_kernel_free(cls C.mlx_fast_metal_kernel)
fn C.mlx_fast_metal_kernel_apply(outputs &C.mlx_vector_array, cls C.mlx_fast_metal_kernel, inputs C.mlx_vector_array, config C.mlx_fast_metal_kernel_config, stream C.mlx_stream) int
fn C.mlx_fast_rms_norm(res &C.mlx_array, x C.mlx_array, weight C.mlx_array, eps f32, s C.mlx_stream) int
fn C.mlx_fast_rope(res &C.mlx_array, x C.mlx_array, dims int, traditional bool, base C.mlx_optional_float, scale f32, offset int, freqs C.mlx_array, s C.mlx_stream) int
fn C.mlx_fast_rope_dynamic(res &C.mlx_array, x C.mlx_array, dims int, traditional bool, base C.mlx_optional_float, scale f32, offset C.mlx_array, freqs C.mlx_array, s C.mlx_stream) int
fn C.mlx_fast_scaled_dot_product_attention(res &C.mlx_array, queries C.mlx_array, keys C.mlx_array, values C.mlx_array, scale f32, mask_mode &char, mask_arr C.mlx_array, sinks C.mlx_array, s C.mlx_stream) int
fn C.mlx_async_eval(outputs C.mlx_vector_array) int
fn C.mlx_checkpoint(res &C.mlx_closure, fun C.mlx_closure) int
fn C.mlx_custom_function(res &C.mlx_closure, fun C.mlx_closure, fun_vjp C.mlx_closure_custom, fun_jvp C.mlx_closure_custom_jvp, fun_vmap C.mlx_closure_custom_vmap) int
fn C.mlx_custom_vjp(res &C.mlx_closure, fun C.mlx_closure, fun_vjp C.mlx_closure_custom) int
fn C.mlx_eval(outputs C.mlx_vector_array) int
fn C.mlx_jvp(res_0 &C.mlx_vector_array, res_1 &C.mlx_vector_array, fun C.mlx_closure, primals C.mlx_vector_array, tangents C.mlx_vector_array) int
fn C.mlx_value_and_grad(res &C.mlx_closure_value_and_grad, fun C.mlx_closure, argnums &int, argnums_num usize) int
fn C.mlx_vjp(res_0 &C.mlx_vector_array, res_1 &C.mlx_vector_array, fun C.mlx_closure, primals C.mlx_vector_array, cotangents C.mlx_vector_array) int
fn C.mlx_detail_vmap_replace(res &C.mlx_vector_array, inputs C.mlx_vector_array, s_inputs C.mlx_vector_array, s_outputs C.mlx_vector_array, in_axes &int, in_axes_num usize, out_axes &int, out_axes_num usize) int
fn C.mlx_detail_vmap_trace(res_0 &C.mlx_vector_array, res_1 &C.mlx_vector_array, fun C.mlx_closure, inputs C.mlx_vector_array, in_axes &int, in_axes_num usize) int
fn C.mlx_compile(res &C.mlx_closure, fun C.mlx_closure, shapeless bool) int
fn C.mlx_detail_compile(res &C.mlx_closure, fun C.mlx_closure, fun_id usize, shapeless bool, constants &u64, constants_num usize) int
fn C.mlx_detail_compile_clear_cache() int
fn C.mlx_detail_compile_erase(fun_id usize) int
fn C.mlx_disable_compile() int
fn C.mlx_enable_compile() int
fn C.mlx_set_compile_mode(mode int) int
fn C.mlx_load_reader(res &C.mlx_array, in_stream C.mlx_io_reader, s C.mlx_stream) int
fn C.mlx_load(res &C.mlx_array, file &char, s C.mlx_stream) int
fn C.mlx_load_gguf(gguf &C.mlx_io_gguf, file &char, s C.mlx_stream) int
fn C.mlx_load_safetensors_reader(res_0 &C.mlx_map_string_to_array, res_1 &C.mlx_map_string_to_string, in_stream C.mlx_io_reader, s C.mlx_stream) int
fn C.mlx_load_safetensors(res_0 &C.mlx_map_string_to_array, res_1 &C.mlx_map_string_to_string, file &char, s C.mlx_stream) int
fn C.mlx_save_writer(out_stream C.mlx_io_writer, a C.mlx_array) int
fn C.mlx_save(file &char, a C.mlx_array) int
fn C.mlx_save_gguf(file &char, gguf C.mlx_io_gguf) int
fn C.mlx_save_safetensors_writer(in_stream C.mlx_io_writer, param C.mlx_map_string_to_array, metadata C.mlx_map_string_to_string) int
fn C.mlx_save_safetensors(file &char, param C.mlx_map_string_to_array, metadata C.mlx_map_string_to_string) int
fn C.mlx_clear_cache() int
fn C.mlx_get_active_memory(res &usize) int
fn C.mlx_get_cache_memory(res &usize) int
fn C.mlx_get_memory_limit(res &usize) int
fn C.mlx_get_peak_memory(res &usize) int
fn C.mlx_reset_peak_memory() int
fn C.mlx_set_cache_limit(res &usize, limit usize) int
fn C.mlx_set_memory_limit(res &usize, limit usize) int
fn C.mlx_set_wired_limit(res &usize, limit usize) int
fn C.mlx_distributed_all_gather(res &C.mlx_array, x C.mlx_array, group C.mlx_distributed_group, S C.mlx_stream) int
fn C.mlx_distributed_all_max(res &C.mlx_array, x C.mlx_array, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_distributed_all_min(res &C.mlx_array, x C.mlx_array, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_distributed_all_sum(res &C.mlx_array, x C.mlx_array, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_distributed_recv(res &C.mlx_array, shape &int, shape_num usize, dtype int, src int, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_distributed_recv_like(res &C.mlx_array, x C.mlx_array, src int, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_distributed_send(res &C.mlx_array, x C.mlx_array, dst int, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_distributed_sum_scatter(res &C.mlx_array, x C.mlx_array, group C.mlx_distributed_group, s C.mlx_stream) int
fn C.mlx_node_namer_new() C.mlx_node_namer
fn C.mlx_node_namer_free(namer C.mlx_node_namer) int
fn C.mlx_node_namer_set_name(namer C.mlx_node_namer, arr C.mlx_array, name &char) int
fn C.mlx_node_namer_get_name(name &&char, namer C.mlx_node_namer, arr C.mlx_array) int
fn C.mlx_metal_is_available(res &bool) int
fn C.mlx_metal_start_capture(path &char) int
fn C.mlx_metal_stop_capture() int
fn C.mlx_cuda_is_available(res &bool) int
fn C.mlx_version(str_ &C.mlx_string) int
fn C.mlx_export_function(file &char, fun C.mlx_closure, args C.mlx_vector_array, shapeless bool) int
fn C.mlx_export_function_kwargs(file &char, fun C.mlx_closure_kwargs, args C.mlx_vector_array, kwargs C.mlx_map_string_to_array, shapeless bool) int
fn C.mlx_function_exporter_new(file &char, fun C.mlx_closure, shapeless bool) C.mlx_function_exporter
fn C.mlx_function_exporter_free(xfunc C.mlx_function_exporter) int
fn C.mlx_function_exporter_apply(xfunc C.mlx_function_exporter, args C.mlx_vector_array) int
fn C.mlx_function_exporter_apply_kwargs(xfunc C.mlx_function_exporter, args C.mlx_vector_array, kwargs C.mlx_map_string_to_array) int
fn C.mlx_imported_function_new(file &char) C.mlx_imported_function
fn C.mlx_imported_function_free(xfunc C.mlx_imported_function) int
fn C.mlx_imported_function_apply(res &C.mlx_vector_array, xfunc C.mlx_imported_function, args C.mlx_vector_array) int
fn C.mlx_imported_function_apply_kwargs(res &C.mlx_vector_array, xfunc C.mlx_imported_function, args C.mlx_vector_array, kwargs C.mlx_map_string_to_array) int
